### ISSUE TITLE
If it's named after a plant fungus why not aecium which is a rust fungus

### ISSUE THREAD

**Issue by alkeryn** [crablang/crab#1]
![Screenshot_20230413-171935_Brave](https://user-images.githubusercontent.com/11599075/231807177-97235f33-b0c9-4d5e-8117-602e77ed7eeb.jpg)

Idk also that would avoid the .cl file extension which is already taken by common lisp.

**Comment by trvswgnr** [comment]
we chose "crablang" because we love ferris, a mascot which we can use freely, and because many have started referring to r*st as "that crab language."

**Comment by rostrusty** [comment]
This language isn't named after a fungus. This language is named after a language named after a fungus.

**Comment by Samathingamajig** [comment]
I agree with [rostcrablangy](https://github.com/rostrusty)

**Comment by alkeryn** [comment]
@rostrusty oh my bad, the description could leave some ambiguity imo haha.
well crab is good, file extension could be .cr
i wonder where this will go.

**Comment by fazibear** [comment]
.cr is a https://crystal-lang.org/ extension. 
What about .🦀 ?

**Comment by alkeryn** [comment]
@fazibear oh man i haven't heard about that one in a long time !

**Comment by nanjizal** [comment]
the default extension should be  ```.crab``` it is human readable and arguably better than rs.  Then any 'new' features like ternary would require ```.crab``` extension and old ones could use ```.rs``` only if user wanted to keep compatibility.
