### ISSUE TITLE
Publish Book

### ISSUE THREAD

**Issue by Meow-purr** [crablang/crab#100]
try out no starch

**Comment by pinkforest** [comment]
Nothing to do with us / development here. Anyone can write one and publish one since there is no trademark anyone owns.

**Comment by Meow-purr** [comment]
i mean https://github.com/crablang/book

**Comment by pinkforest** [comment]
Ok. That's in process. There is already book repository now - it should come on as book. or doc. soon.

Moving this issue there - feel free to send PR's there.

**Comment by Meow-purr** [comment]
but therese no issue tracker for the crabs to crabplain

**Comment by pinkforest** [comment]
True - Not yet no. Will move there when re-enabled as the repo is being detached. PR's there would be appreciated in the meantime.

Also please feel free to use Discussions for any Ideas that don't involve what we are mainly doing e.g. documentation, experimental etc. - we are trying to keep the developmen track laser focused with clear issues what is needed here now - Thanks.
