### ISSUE TITLE
Isn't it time to archive this project?

### ISSUE THREAD

**Issue by aurora1369** [crablang/crab#108]
As we all know, almost all of the concerns of the community that led to the creation of this project appears to have been addressed.
With the recent [dismantling of the core team](https://blog.rust-lang.org/2023/06/20/introducing-leadership-council.html), and the new re-architecture of the internal governance structure, it appears the processes(and/or the atmosphere) that's been causing many of the past dramas and science fictions has ended.

P.S.: Some other day some sh*t happens and I can't even remove this issue!

**Comment by ZeroAurora** [comment]
From my personal perspective, I would like to see some language thar can compete with Rust, but with an easier syntax and a better community. However I don't quite think that it's a crablang goal.
I would like to see a friendlier and unified Rust community in the near future. Let's see how the new core team does!

**Comment by martin-braun** [comment]
> P.S.: Some other day some sh*t happens and I can't even remove this issue!

wdym?

**Comment by lilith13666** [comment]
@ZeroAurora
> From my personal perspective, I would like to see some language that can compete with Rust, but with an easier syntax and a better community. However I don't quite think that it's a crablang goal.

Crablang is definitely not what you're looking for. This project was originally made just to protest the trademark policy coming from the Rust Foundation. Nobody's concerned with the Rust language's complexity. If Rust feels way too complicated, try writing LLVM IR.

> I would like to see a friendlier and unified Rust community in the near future.

The community is and always was unified and friendly. It was the governance teams who "were" not.

> Let's see how the new core team does!

The core team is [dismantled](https://blog.rust-lang.org/2023/06/20/introducing-leadership-council.html).
Please also take a look at [here](https://users.rust-lang.org/t/why-is-there-so-much-mismanagement-in-the-rust-foundation-and-core-team/94822) for more in-depth discussion.

**Comment by lilith13666** [comment]
@martin-braun
> wdym?

By sh*t happening, I mean The Rust governance teams cause another new trouble for the community. But GitHub isn't like Reddit or somewhere else, I can't remove this issue, if I see it become irrelavant.

**Comment by ZeroAurora** [comment]
> @ZeroAurora
> 
> > From my personal perspective, I would like to see some language that can compete with Rust, but with an easier syntax and a better community. However I don't quite think that it's a crablang goal.
> 
> Crablang is definitely not what you're looking for. This project was originally made just to protest the trademark policy coming from the Rust Foundation. Nobody's concerned with the Rust language's complexity. If Rust feels way too complicated, try writing LLVM IR. For example, C is not only more complicated, it's unsafe, old-fashioned and [mostly slower](https://programming-language-benchmarks.vercel.app/c-vs-rust).
> 
> > I would like to see a friendlier and unified Rust community in the near future.
> 
> The community is and always was unified and friendly. It was the governance teams who "were" not.
> 
> > Let's see how the new core team does!
> 
> The core team is [dismantled](https://blog.rust-lang.org/2023/06/20/introducing-leadership-council.html). Please also take a look at [here](https://users.rust-lang.org/t/why-is-there-so-much-mismanagement-in-the-rust-foundation-and-core-team/94822) for more in-depth discussion.

Yes I have some errors in my comments. Thanks for your indepth explanation!

**Comment by apiraino** [comment]
On crablang.org I read:

> The Crab (or “CrabLang”) community fork was created as a lighthearted yet measured response to the growing concerns within the community about the influence of corporations, restrictive trademark policy proposed by the foundation, and internal political decisions

You folks made your point and people got it but now I think it's time to fold it. There are people (admittedly ill-informed) that are taking this joke seriously, see [here](https://www.infoworld.com/article/3701230/rust-language-project-revamps-governance.html) and [here](https://libreddit.freedit.eu/r/rust/comments/14mh824/i_introduced_rust_at_work/). I am sure the intent of this repository is not to cause harm or damage the project or its community (it is clearly spelled out on your website).

If you _really_ have something to say, I would perhaps encourage you to follow the work that is being done by the Rust project (to address the open issues) and participate in a more constructive way.

Disclosure: I am a contributor to the Rust project, I am speaking only for myself and am not representing anyone else.

**Comment by trvswgnr** [comment]
hey all, appreciate the thoughts and the chat here.

@lilith13666 i've seen the changes in rust's governance—i'm cautiously optimistic—but crablang isn't just about that. there are issues with the corporate influence, internal politics, and the trademark policy as well. not that crablang's existence is hanging on the trademark policy, but it was a big part of why we started this. has there been any solidification of a policy or clarification concerning that?

@ZeroAurora crablang wasn't made to compete with rust on syntax or community vibes. but we think having alternatives is cool, it brings diversity and choice. it's not about replacing rust, but giving another option for those who share our concerns.

@apiraino thanks so much for your perspective as a rust contributor. i assure you, crablang isn't a joke, nor was it made to cause harm. we might have fun with it, but our concerns are very real. we're not out to damage rust or the community. options can only be a good thing for the ecosystem.

beyond that, would it be such a bad thing to have a place where people feel they can try new ideas without the intimidation that inherently comes from trying to contribute to the upstream project?

everyone's welcome to join, whether that's contributing to the project or participating in discussions - thanks again

**Comment by trvswgnr** [comment]
ok going to close this now thx again
