### ISSUE TITLE
Is crab lang dead?

### ISSUE THREAD

**Issue by blueOkiris** [crablang/crab#118]
I've seen no recent issues or PRs and nothing on social media.

Is crab lang a dead project? Should it be archived?

**Comment by Craige** [comment]
_\*crickets\*_

**Comment by TeaCrab** [comment]
With enough crabs speaking it it will never die.

**Comment by trvswgnr** [comment]
@blueOkiris @Craige sorry i've been on vacation 😅 crablang simply provides an open alternative for the community, so as long as there are people that want a rust that *we* control, it will continue to exist
