### ISSUE TITLE
Remove references of R*st

### ISSUE THREAD

**Issue by nonetrix** [crablang/crab#18]
As it stands many references to R*st can be found even in the issue templates, this is not a issue for now to my understanding since it's just a draft but might be in the future. All references of R*st should be removed to avoid issues with the R*st Foundation. Thanks for the crabs! Have some more crabs for the effort

![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)
![wheatly-crab](https://user-images.githubusercontent.com/45698918/232184390-727f01b4-5c08-4999-86f9-fd7c11c2fab8.gif)

**Comment by nonetrix** [comment]
While it's not needed maybe we should name our files with something like .cl or something like that since that will mean that it is not 100% compatible with Rust, although a translator could be made but that might cause issues with copyright again

**Comment by krolyxon** [comment]
`.cr` > `.cl` && `.cr` > `.crab`

**Comment by nonetrix** [comment]
I like ```.crab``` the most it's just silly and fun

**Comment by synodriver** [comment]
![crab](https://avatars.githubusercontent.com/u/78263937?v=4)

**Comment by TCROC** [comment]
@nonetrix 

> Also, may I ask is there plans to change the language more than this, or just keeping faithful to the original and tracking upstream 

upstream tracking is the plan :)

I proposed a file name extension translator command / tool here:

https://github.com/crablang/crab/issues/20

Love the '.crab' idea ❤️

**Comment by trvswgnr** [comment]
we're not going to remove every instance of the word "rust" in the codebase. there are just too many cases where it would break things and we'd need an incredibly robust way to test it. changing instances in markdown, etc should be fine though.

**Comment by Meow-purr** [comment]
> I like `.crab` the most it's just silly and fun, I just hope that R*st doesn't go through with the changes or this project remains active and sees adoption

see #53
