### ISSUE TITLE
Is it legal to copy a programming language like this?

### ISSUE THREAD

**Issue by realzhujunhao** [crablang/crab#19]
As a computer science major student who is quite new to dev world, I wonder if such things are allowed.

**Comment by meister03** [comment]
> As a computer science major student who is quite new to dev world, I wonder if such things are allowed.

As long it follows the licensing it is

**Comment by trvswgnr** [comment]
yep! we are free to use, copy, and modify the original language, which has an open source license.

**Comment by sammi-turner** [comment]
Yes, this project is in line with the terms of the original MIT/Apache license.
