### ISSUE TITLE
crabtime

### ISSUE THREAD

**Issue by axiomatic-aardvark** [crablang/crab#2]

**Comment by 0xhiro** [comment]
Wait what???????

**Comment by axiomatic-aardvark** [comment]
I am expressing my joy 🦀

**Comment by boehs** [comment]
it's crabbin time!

**Comment by nonetrix** [comment]
So true
https://youtu.be/watch?v=J6iE_RpqYzo

**Comment by o-agassizii** [comment]
https://www.youtube.com/watch?v=LDU_Txk06tM

🦀 🦀 🦀

**Comment by MostHated** [comment]
Careful guys: this might get you in trouble.

![](https://img.instance.id/tzICbkWJOFgx/direct)
