### ISSUE TITLE
Website share

### ISSUE THREAD

**Issue by halan** [crablang/crab#21]
Currently, the share feature is pointing out to http://example.com.

![image](https://user-images.githubusercontent.com/77821/232237024-ef333492-41ca-46db-82b9-3456f389c59c.jpeg)

**Comment by trvswgnr** [comment]
good find. we also need an social image for twitter, etc... i'll move this to [the crablang site repo](https://github.com/crablang/crablang-site)

**Comment by trvswgnr** [comment]
pushed an update for this, if anyone wants to test.

**Comment by aar9nk** [comment]
Also, just saw that 
https://crablang.org/community
Is erroring with a 404 :) It was linked in the README so I thought I'd check it out!

Sorry I have no way of testing the above

**Comment by trvswgnr** [comment]
we can make a redirect for /community. also it looks like astro doesn't come with support for twitter social thumbnail by default so that's not working. we should continue this on the other repo.

**Comment by trvswgnr** [comment]
btw @aar9nk the link is now https://community.crablang.org
