### ISSUE TITLE
Concern over mascot being too similar with the language named after a plant fungus

### ISSUE THREAD

**Issue by newholder** [crablang/crab#26]
Not a lawyer but I think the mascot might be too similar that monster energy grade lawyer might try to sue. so maybe modify it a lot?

**Comment by dogue** [comment]
Ferris is creative commons. The Foundation holds no trademark over it, to my understanding.

**Comment by TCROC** [comment]
Fortunately The Foundation has made it explicitly clear that we are free to use the Ferris.

🦀

Long live the Crab!

**Comment by newholder** [comment]
Ooooo nice. LONG LIVE THE CRAB
