### ISSUE TITLE
Can I use crab logo?

### ISSUE THREAD

**Issue by WOOB4T** [crablang/crab#30]
Hello sirs, thank you for the fork. It is a very nice fork and I am looking to incorporate it into my daily programming but I like to use the logo for purposes related to microblogging and was wondering if it was ok? Is it ok to edit the logo to a theme too?

**Comment by TCROC** [comment]
> Hello sirs, thank you for the fork. It is a very nice fork and I am looking to incorporate it into my daily programming but I like to use the logo for purposes related to microblogging and was wondering if it was ok? Is it ok to edit the logo to a theme too? 

Absolutely! Use it however u like! :) it is something CrabLang explicitly encourages!

**Comment by trvswgnr** [comment]
absolutely! the original ferris mascot was made public domain by the original author, and the modified version i designed can be used or modified however you'd like
