### ISSUE TITLE
Consider enabling GitHub discussions

### ISSUE THREAD

**Issue by waynebloss** [crablang/crab#35]
Please consider enabling discussions here, for people who do not like Discord [for a variety](https://www.google.com/search?q=discord+sucks+for+software+projects)… [of reasons](https://news.ycombinator.com/item?id=28550566)

**Comment by TCROC** [comment]
I don't see any harm in GitHub discussions.  What do you think @trvswgnr ?

**Comment by trvswgnr** [comment]
i enabled discussions 🦀
