### ISSUE TITLE
Fungal references in repository should be replaced with crab

### ISSUE THREAD

**Issue by ryao** [crablang/crab#42]
I see a number of references to fungi in the repository just by looking at a single subdirectory:

https://github.com/crablang/crab/tree/master/compiler

I suggest replacing them with the word crab.

**Comment by trvswgnr** [comment]
we initially tried to do a full replace throughout the codebase but there are too many references to external sources and it would be a nightmare to debug everything that breaks. the code itself has an open license so it's not really necessary to replace all instances of the language crab was forked from.
