### ISSUE TITLE
Rename Cargo to Crusty

### ISSUE THREAD

**Issue by TCROC** [crablang/crab#5]
Rename cargo to crusty.  Now we have crusty building the crab language.  May or may not be inspired by some yellow square with the last name Robert or something 🟨 :)

### Update 1

Ok so there are 2 current popular proposals:

### Spongebob Theme:

cargo -> crusty or krusty
rust -> crab
rustc -> crabc
rustfmt -> crabfmt
clippy -> fiddler
crate -> patty

### Crab Theme:

cargo -> crabgo
rust -> crab
rustc -> crabc
rustfmt -> crabfmt
clippy -> crabby
crate -> barrel, cage, idk. I haven't seen any crab[some term here] for this one yet.

I know I proposed the Spongebob theme, but I'm actually leaning towards the crab theme for simplicity and easy to remember commands / tools.

BUT

I propose that if we go with the crab theme, we include an easter egg:

``crabgo sponge``

It will alias all tools / commands to sponge bob related things :)

I'll keep updating this as we make progress with the discussion around the issue :).  If anyone has any ideas for a crate -> crab[something] post below! :)

**Comment by GavHern** [comment]
i dont think it would be a wise legal decision to call it c\*\*\*\*y

**Comment by jmjoy** [comment]
I prefer to `crabgo`.

**Comment by katsuki-yuri** [comment]
How about vessel?)

**Comment by axiomatic-aardvark** [comment]
craby?

**Comment by dogue** [comment]
If we're sticking to crab puns, "trap" and "pot" are options. I don't particularly like either though.

**Comment by Artoria2e5** [comment]
SpongeBob reference might be the way to go, since there are a lot of sea names to play with.
* Cargo -> Crusty (nah, I don't think the substring is a trademark issue)
* crate -> patty (why not) &ndash; [barrels](https://twitter.com/marilia_cloud/status/1646831669389717504) is better
* clippy -> plankton (lol)

**Comment by dogue** [comment]
I'm kinda into patty for packages

**Comment by TCROC** [comment]
I too am into patty for packages

**Comment by dogue** [comment]
How about "fiddler" for clippy?

**Comment by TCROC** [comment]
Is that referencing this?
https://scratchpad.fandom.com/wiki/Fiddler_on_the_Roof_(1971)/Spongebob

**Comment by dogue** [comment]
It's referencing this tweet (https://twitter.com/founderjake/status/1646513209220939786) and the existence of fiddler crabs.

**Comment by TCROC** [comment]
I like fiddler :).  What do you think @Artoria2e5 ?

**Comment by TCROC** [comment]
Tom summarize current proposal:

cargo -> crusty
crate -> patty
clippy -> fiddler

**Comment by TCROC** [comment]
Ok so there are 2 current popular proposals:

### Spongebob Theme:

cargo -> crusty
rust -> crab
rustc -> crabc
rustfmt -> crabfmt
clippy -> fiddler
crate -> patty

### Crab Theme:

cargo -> crabgo
rust -> crab
rustc -> crabc
rustfmt -> crabfmt
clippy -> crabby
crate -> barrel, cage, idk.  I haven't seen any crab<some term here> for this one yet.

I know I proposed the Spongebob theme, but I'm actually leaning towards the crab theme for simplicity and easy to remember commands / tools.

BUT

I propose that if we go with the crab theme, we include an easter egg:

``crabgo sponge``

It will alias all tools / commands to sponge bob related things :)

**Comment by GavHern** [comment]
> ### Spongebob Theme:
> 
> 
> 
> cargo -> crusty

shouldn't it be "krusty" then?

**Comment by TCROC** [comment]
> > ### Spongebob Theme:
> > cargo -> crusty
> 
> shouldn't it be "krusty" then?

Correct, I was trying to keep everything with "c" starting out.  So kinda a play on words.  I'm leaning more towards crabgo personally now anyways tho.

If we are going the "easter egg alias" route for spongebob stuff I'd be just fine with using "krusty" instead :)

**Comment by dogue** [comment]
I like rustacean -> crabgoon

**Comment by TCROC** [comment]
> I like rustacean -> crabgoon

Love it! ❤️

**Comment by trvswgnr** [comment]
lol does anyone know how we can avoid upstream commits/prs from closing our issues?
