### ISSUE TITLE
crab sounds like crap

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [crablang/crab#54]
bro what is wrong with you?

rust, rusty fucking rust.. 

now: crab, crap, shit, garbage.

was there no other way?

**Comment by UnlimitedKaos** [comment]
If crab == crap, then why is the endgame of evolution crabs? Imo nature proves crab is viable.

**Comment by trvswgnr** [comment]
lol thank you for your feedback. i will send your remarks to HR.
