### ISSUE TITLE
you're probably infringing the Rust trademark by using their logo

### ISSUE THREAD

**Issue by jeremyBanks** [crablang/crab#55]
👍👍

**Comment by Lissy93** [comment]
I think there's some mixup between the Rust mascot and the Rust logo here.

### Mascot - Can Use ✅

As far as I know (someone correct me if I'm mistaken), the crab logo (Ferris the Rustacean) is Rust's unofficial mascot, and was released into the public domain, the creator (Karen Rustad Tölva) has waived all copyright and related or neighboring rights to Ferris

<img width="128" src="https://www.rustacean.net/assets/rustacean-orig-noshadow.svg" />

### Logo - Cannot Use ❌

Whereas the Rust logo is distributed under a Creative Commons Attribute-NonCommercial-NoDerivatives license. Which should permit you to reproduce the work as-is for noncommercial purposes, with attribution, but does not allow creating or distributing derived works.

<img width="128" src="https://raw.githubusercontent.com/rust-lang/rust-artwork/master/logo/rust-logo-128x128-blk-v2.png" />

**Comment by Lissy93** [comment]
Ferris is iconic, and isn't associated with the Rust Foundation. I think it would be a shame to see him go.
On a side note, I love the mischievous knife crab-lang Ferris, created by @trvswgnr (?) - nice work :)

<img width="128" src="https://user-images.githubusercontent.com/8974888/231858967-7c37bf1e-335b-4f5a-9760-da97be9f54bb.png" />

---

> Green would be good?

But crabs aren't green.... (though I did [make a green one](https://github.com/Lissy93/AdGuardian-Term) this weekend, so I'm not one to judge! 😉🦀)

**Comment by trvswgnr** [comment]
> Ferris is iconic, and isn't associated with the Rust Foundation. I think it would be a shame to see him go. On a side note, I love the mischievous knife crab-lang Ferris, created by @trvswgnr (?) - nice work :)
> 
> <img alt="" width="128" src="https://user-images.githubusercontent.com/8974888/231858967-7c37bf1e-335b-4f5a-9760-da97be9f54bb.png">
> 
> > Green would be good?
> 
> But crabs aren't green.... (though I did [make a green one](https://github.com/Lissy93/AdGuardian-Term) this weekend, so I'm not one to judge! 😉🦀)

thanks! it's the pinnacle of my graphic design career really 😂

**Comment by Meow-purr** [comment]
> I think there's some mixup between the Rust mascot and the Rust logo here. Crab lang isn't using the Rust logo anywhere (or at least I haven't seen it used), they're using a modified version of the Rust mascot, Ferris - which is allowed.
> 
> As far as I know (someone correct me if I'm mistaken), the two work like this:
> ### Mascot - Can Use white_check_mark
> 
> The crab (Ferris the Rustacean) is Rust's unofficial mascot, which was released into the public domain, by the creator (Karen Rustad Tölva) who has waived all copyright and related or neighboring rights to Ferris
> 
> <img alt="" width="128" src="https://camo.githubusercontent.com/f5926ca7e80a979bcc75b7bbd98e835370afb67695896075551c81a507d1f595/68747470733a2f2f7777772e72757374616365616e2e6e65742f6173736574732f72757374616365616e2d6f7269672d6e6f736861646f772e737667">
> ### Logo - Cannot Use x
> 
> Whereas the Rust logo is distributed under a Creative Commons Attribute-NonCommercial-NoDerivatives license. Which although should permit you to reproduce the work as-is for noncommercial purposes, with attribution, does not allow creating or distributing derived works.
> 
> img alt="" width="128" src="https://raw.githubusercontent.com/rust-lang/rust-artwork/master/logo/rust-logo-128x128-blk-v2.png">
>@lissy93
i think @Lissy93  just broke the trade mark pollice ( delleted it from my comment check the orignal)

**Comment by Lissy93** [comment]
> i think @Lissy93 just broke the trade mark pollice ( delleted it from my comment check the orignal)

@Meow-purr  - So long as it's attributed (which it is), and not modified (which it isn't) no trade mark policies have been violated here. Source [Rust Foundation's Logo Policy](https://foundation.rust-lang.org/policies/logo-policy-and-media-guide/).
