### ISSUE TITLE
Can the knife in the logo be removed/changed?

### ISSUE THREAD

**Issue by firatoezcan** [crablang/crab#59]
I'm the last one to not find it funny but I think maybe something like a water gun or an eyepatch would be less "knife in logo" 🦀

**Comment by onehex** [comment]
knife is a killer move by crablang.
i support knife.

**Comment by Traneptora** [comment]
![image](https://github.com/crablang/crab/assets/1342577/bcbbcda1-dbe9-488f-9b25-011cf8ca21ab)

**Comment by noctisatrae** [comment]
Love this picture!

**Comment by asyncfn** [comment]
You can't cover up homophobic behavior in your team!
![crab](https://github.com/crablang/crab/assets/103520577/0908daa5-fdd5-4567-9660-3e01bc4f8dd1)
![crab2](https://github.com/crablang/crab/assets/103520577/904d544a-b781-403a-80e6-dbe7306c2fc2)
