### ISSUE TITLE
Trenacisation

### ISSUE THREAD

**Issue by erkinalp** [crablang/crab#60]
Crates transport pieces of code, and trains are the ultimate form of the transportation. Hence, crates should be renamed into trains.

**Comment by Meow-purr** [comment]
this should be in crabgo repo

**Comment by erkinalp** [comment]
@Meow-purr that one does not accept tickets

**Comment by Meow-purr** [comment]
> @Meow-purr that one does not accept tickets
@erkinalp 

@crablang shuold accept tickets for crabgo

**Comment by trvswgnr** [comment]
it should accept issues now

**Comment by TheArcaneBrony** [comment]
@erkinalp usually you would load the crates onto the train, not replace the crates themselves with trains.

**Comment by trvswgnr** [comment]
"containers" is a little ambiguous lol

going to close this, but can continue in [a Discussion](https://github.com/crablang/crab/discussions/new/choose) if you'd like.

**Comment by Meow-purr** [comment]
reopen

**Comment by pinkforest** [comment]
Please use the existing issue and stop spamming.
