### ISSUE TITLE
.🚂 for trains

### ISSUE THREAD

**Issue by Meow-purr** [crablang/crab#64]
.🚂 for trains(#60 and https://github.com/crablang/crab/issues/53#issuecomment-1569062505 and https://github.com/crablang/crab/issues/53#issuecomment-1569071278)
 sub task of #53

**Comment by asyncfn** [comment]
You can't cover up homophobic behavior in your team!
![crab](https://github.com/crablang/crab/assets/103520577/8295a265-5c7b-43fe-b0ea-22d7760f418a)
![crab2](https://github.com/crablang/crab/assets/103520577/49376f02-c1c6-4c17-9822-dec85ffe7c5c)
