### ISSUE TITLE
what‘s the difference and relationship between crab and rust?

### ISSUE THREAD

**Issue by miaomiao1992** [crablang/crab#72]
I am a green hand,and i really don't know the difference and relationship between crab and rust.

**Comment by lilith13666** [comment]
@miaomiao1992 Crab is based on Rust. It's more of a harmless protestware, just to put pressure on the Rust foundationto drop some of their bad governance practices.

Might find it interesting: https://www.reddit.com/r/rust/comments/140ruz2

**Comment by trvswgnr** [comment]
> @miaomiao1992 Crab is based on Rust. It's more of a harmless protestware, just to put pressure on the Rust foundationto drop some of their bad governance practices.
> 
> Might find it interesting: https://www.reddit.com/r/rust/comments/140ruz2

unfortunately it looks like /r/rust most removed the post 😬

there is more info about Crab on the the website @miaomiao1992 😊 https://crablang.org

**Comment by lilith13666** [comment]
> > @miaomiao1992 Crab is based on Rust. It's more of a harmless protestware, just to put pressure on the Rust foundationto drop some of their bad governance practices.
> > Might find it interesting: https://www.reddit.com/r/rust/comments/140ruz2
> 
> unfortunately it looks like /r/rust most removed the post 😬
> 
> there is more info about Crab on the the website @miaomiao1992 😊 https://crablang.org

I ran a poll on the /r/rust subreddit titled 'Do you think the Rust Foundation is damaging the future of the Rust language?
'
Out of a total of 47 votes, 25 people said 'Yes'.

I reached out the moderation team to know why the post was removed. Well, they said it was auto-removed by a moderation bot. Anyway, not even this talk made them think that they should probably get the post back.

Though, I should note, as mentioned and directly confirmed by specific individuals, not all the bad practices is coming from the Rust Foundation. The Rust core team is just going shoulder to shoulder with them.
