### ISSUE TITLE
Feature: `crabup.sh` for installing crab lang

### ISSUE THREAD

**Issue by jpmcb** [crablang/crab#78]
Hi all - would love if there was an easy way to install crab via `crabup.sh` (much like there is a `rustup.sh` for rust).

Looks like `crabup.sh` is already registered; do one of the maintainers here have it and could we take use of that for installing crab?

**Comment by asyncfn** [comment]
You can't cover up homophobic behavior in your team!
![crab](https://github.com/crablang/crab/assets/103520577/8900a15c-2245-4e0f-b11a-5670aeeeaef3)
![crab2](https://github.com/crablang/crab/assets/103520577/86444830-eb44-485f-90c6-1e3bf4130081)

**Comment by pinkforest** [comment]
This already works :)

See; https://github.com/crablang/crabup

Also see CI action here which uses it: https://github.com/rinse-repeat/crab-toolchain

I have a CI for it running as well: https://github.com/rinse-repeat/crab-toolchain/actions/runs/5233206187

Windows one needs fixing and currently it just renames rust bins - which we will need a pipeline in the future.

**Comment by pinkforest** [comment]
If someone has some time to contribute - there is the issue open for fixing the current Windows quick installer
- https://github.com/crablang/crablang-site/issues/25
