### ISSUE TITLE
Homophobia among crab team

### ISSUE THREAD

**Issue by asyncfn** [crablang/crab#84]
You claim to have better standards than the Rust team. I expect that you will take action so this outrageous situation (your moderator is posting homophobic content) would never happen again

https://twitter.com/AstraKernel/status/1667562407793950720

**Comment by asyncfn** [comment]
There are tries to cover up the homophobic scandal, so I'm posting a screenshot
![crab](https://github.com/crablang/crab/assets/103520577/98f70735-bdd4-4fd4-afe9-9baafdaf1a9b)

**Comment by rlidwka** [comment]
People are free to write whatever they want in their private twitter accounts, and you are welcome to unfollow the accounts you don't like the content of.

Are you overreacting or just trolling?

**Comment by asyncfn** [comment]
> People are free to write whatever they want in their private twitter accounts, and you are welcome to unfollow the accounts you don't like the content of.
> 
> Are you overreacting or just trolling?

I'm expecting here high standards of behavior.

1 explanation why such person was allowed to work in moderation.
2 I didn't saw any apology to people who could be harmed by this behaviour.
